const countryList = {
    Afghanistan: '4.5',
    Albania: '1',
    Algeria: '1',
    'American Samoa': '-11',
    Andorra: '1',
    Angola: '1',
    Antarctica: '-2',
    'Antigua and Barbuda': '-4',
    Argentina: '-3',
    Armenia: '4',
    Aruba: '-4',
    Ascension: '0',
    'Australia North': '9.5',
    'Australia South': '10',
    'Australia West': '8',
    'Australia East': '10',
    Austria: '1',
    Azerbaijan: '3',
    Bahamas: '-5',
    Bahrain: '3',
    Bangladesh: '6',
    Barbados: '-4',
    Belarus: '2',
    Belgium: '1',
    Belize: '-6',
    Benin: '1',
    Bermuda: '-4',
    Bhutan: '6',
    Bolivia: '-4',
    'Bosnia Herzegovina': '1',
    Botswana: '2',
    'Brazil West': '-4',
    'Brazil East': '-3',
    'British Virgin Islands': '-4',
    Brunei: '8',
    Bulgaria: '2',
    'Burkina Faso': '0',
    Burundi: '2',
    Cambodia: '7',
    Cameroon: '1',
    'Canada Central': '-6',
    'Canada Eastern': '-5',
    'Canada Mountain': '-7',
    'Canada Pacific': '-8',
    'Canada Newfoundland': '-3.5',
    'Cape Verde': '-1',
    'Cayman Islands': '-5',
    'Central African Rep': '1',
    'Chad Rep': '1',
    Chile: '-4',
    China: '8',
    'Christmas Is.': '-10',
    Colombia: '-5',
    Congo: '1',
    'Cook Is.': '-10',
    'Costa Rica': '-6',
    Croatia: '1',
    Cuba: '-5',
    Cyprus: '2',
    'Czech Republic': '1',
    Denmark: '1',
    Djibouti: '3',
    Dominica: '-4',
    'Dominican Republic': '-4',
    Ecuador: '-5',
    Egypt: '2',
    'El Salvador': '-6',
    'Equatorial Guinea': '1',
    Eritrea: '3',
    Estonia: '2',
    Ethiopia: '3',
    'Faeroe Islands': '0',
    'Falkland Islands': '-4',
    'Fiji Islands': '12',
    Finland: '2',
    France: '1',
    'French Antilles (Martinique)': '-3',
    'French Guinea': '-3',
    'French Polynesia': '-10',
    'Gabon Republic': '1',
    Gambia: '0',
    Georgia: '4',
    Germany: '1',
    Ghana: '0',
    Gibraltar: '1',
    Greece: '2',
    Greenland: '-3',
    Grenada: '-4',
    Guadeloupe: '-4',
    Guam: '10',
    Guatemala: '-6',
    'Guinea-Bissau': '0',
    Guinea: '0',
    Guyana: '-3',
    Haiti: '-5',
    Honduras: '-6',
    'Hong Kong': '8',
    Hungary: '1',
    Iceland: '0',
    India: '5.5',
    'Indonesia Central': '8',
    'Indonesia East': '9',
    'Indonesia West': '7',
    Iran: '3.5',
    Iraq: '3',
    Ireland: '0',
    Israel: '2',
    Italy: '1',
    Jamaica: '-5',
    Japan: '9',
    Jordan: '2',
    Kazakhstan: '6',
    Kenya: '3',
    Kiribati: '12',
    'Korea, North': '9',
    'Korea, South': '9',
    Kuwait: '3',
    Kyrgyzstan: '5',
    Laos: '7',
    Latvia: '2',
    Lebanon: '2',
    Lesotho: '2',
    Liberia: '0',
    Libya: '2',
    Liechtenstein: '1',
    Lithuania: '2',
    Luxembourg: '1',
    Macedonia: '1',
    Madagascar: '3',
    Malawi: '2',
    Malaysia: '8',
    Maldives: '5',
    'Mali Republic': '0',
    Malta: '1',
    'Marshall Islands': '12',
    Mauritania: '0',
    Mauritius: '4',
    Mayotte: '3',
    'Mexico Central': '-6',
    'Mexico East': '-5',
    'Mexico West': '-7',
    Moldova: '2',
    Monaco: '1',
    Mongolia: '8',
    Morocco: '0',
    Mozambique: '2',
    Myanmar: '6.5',
    Namibia: '1',
    Nauru: '12',
    Nepal: '5.5',
    Netherlands: '1',
    'Netherlands Antilles': '-4',
    'New Caledonia': '11',
    'New Zealand': '12',
    Nicaragua: '-6',
    Nigeria: '1',
    'Niger Republic': '1',
    'Norfolk Island': '11.5',
    Norway: '1',
    Oman: '4',
    Pakistan: '5',
    Palau: '9',
    'Panama, Republic Of': '-5',
    'Papua New Guinea': '10',
    Paraguay: '-4',
    Peru: '-5',
    Philippines: '8',
    Poland: '1',
    Portugal: '1',
    'Puerto Rico': '-4',
    Qatar: '3',
    'Reunion Island': '4',
    Romania: '2',
    'Russia West': '2',
    'Russia Central 1': '4',
    'Russia Central 2': '7',
    'Russia East': '11',
    Rwanda: '2',
    Saba: '-4',
    Samoa: '-11',
    'San Marino': '1',
    'Sao Tome': '0',
    'Saudi Arabia': '3',
    Senegal: '0',
    'Seychelles Islands': '4',
    'Sierra Leone': '0',
    Singapore: '8',
    Slovakia: '1',
    Slovenia: '1',
    'Solomon Islands': '11',
    Somalia: '3',
    'South Africa': '2',
    Spain: '1',
    'Sri Lanka': '5.5',
    'St Lucia': '-4',
    'St Maarteen': '-4',
    'St Pierre & Miquelon': '-3',
    'St Thomas': '-4',
    'St Vincent': '-4',
    Sudan: '2',
    Suriname: '-3',
    Swaziland: '2',
    Sweden: '1',
    Switzerland: '1',
    Syria: '2',
    Taiwan: '8',
    Tajikistan: '6',
    Tanzania: '3',
    Thailand: '7',
    Togo: '0',
    'Tonga Islands': '13',
    'Trinidad and Tobago': '-4',
    Tunisia: '1',
    Turkey: '2',
    Turkmenistan: '5',
    'Turks and Caicos': '-5',
    Tuvalu: '12',
    Uganda: '3',
    Ukraine: '2',
    'United Arab Emirates': '4',
    'United Kingdom': '0',
    Uruguay: '-3',
    'USA Eastern': '-5',
    'USA Central': '-6',
    'USA Mountain': '-7',
    'USA Pacific': '-8',
    'USA Alaska': '-9',
    'USA Hawaii': '-10',
    Uzbekistan: '5',
    Vanuatu: '11',
    'Vatican City': '1',
    Venezuela: '-4',
    Vietnam: '7',
    'Wallis And Futuna Islands': '12',
    Yemen: '3',
    Yugoslavia: '1',
    Zaire: '2',
    Zambia: '2',
    Zimbabwe: '2',
};

module.exports = countryList;